version: '3'

services:
  web:
    image: nurlan1992/php:php
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./htdocs:/var/www/html
  mysql:
     image: mysql:5.7
     ports:
      - "3306:3306"
     environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql